"use client";

import React, { useState } from "react";

import { PromptCompiler } from "../../../components/Social/PromptCompiler";
import { ErrorBoundary } from "../../../components/Shared/ErrorBoundary";
import { LoadingSpinner } from "../../../components/Shared/LoadingSpinner";
import { useSocialFeeds } from "../../../hooks/useSocialFeeds";

export default function SocialPromptsPage() {
  return (
    <ErrorBoundary>
      <PromptsContent />
    </ErrorBoundary>
  );
}

function PromptsContent() {
  const { compilePrompt, isCompiling, error } = useSocialFeeds();
  const [prompt, setPrompt] = useState("");

  async function handleCompile() {
    if (!prompt.trim()) return;
    await compilePrompt(prompt);
  }

  return (
    <main className="page-container space-y-6 py-8">
      <header className="ui-card p-6">
        <p className="ui-kicker">Compiler Playground</p>
        <h1 className="mt-1 text-3xl font-semibold text-white">Prompt Compiler</h1>
        <p className="mt-2 max-w-3xl text-sm text-slate-300">
          Convert natural-language hypotheses into structured market
          specifications for review before deployment.
        </p>
      </header>

      <section className="ui-card space-y-4 p-5">
        <div>
          <label htmlFor="prompt-input" className="ui-label">
            Natural-language Prompt
          </label>
          <textarea
            id="prompt-input"
            value={prompt}
            onChange={(event) => setPrompt(event.target.value)}
            rows={5}
            placeholder="Will ETH staking APR exceed 6% in Q3 2026?"
            className="ui-textarea"
          />
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <button
            type="button"
            onClick={() => void handleCompile()}
            disabled={isCompiling || !prompt.trim()}
            className="ui-btn ui-btn-primary"
          >
            {isCompiling ? "Compiling..." : "Compile Prompt"}
          </button>
          <p className="text-xs text-slate-400">Production compiler output is validated before market creation</p>
        </div>

        {isCompiling && <LoadingSpinner label="Compiling prompt..." size="sm" />}
        {error && <p className="text-sm text-rose-300">{error.message}</p>}
      </section>

      <section className="ui-card p-5">
        <h2 className="text-lg font-semibold text-white">Structured Output</h2>
        <p className="mt-1 text-sm text-slate-300">
          Intermediate representation generated by the compiler.
        </p>
        <div className="mt-4">
          <PromptCompiler />
        </div>
      </section>
    </main>
  );
}
