"use client";

/**
 * PURPOSE
 * -------
 * Live arbitrage monitoring page.
 *
 * This page:
 * - streams real-time arbitrage opportunities detected by AI agents
 * - visualizes spreads, routes, and confidence
 * - is read-only (execution handled by agents / backend)
 *
 * DESIGN PRINCIPLES
 * -----------------
 * - No mock data
 * - Domain types preserved
 * - UI-only transformations allowed
 * - Defensive UX (loading, error, empty)
 */

// File: frontend/app/yield/arbitrage/page.tsx

"use client";

/**
 * PURPOSE
 * -------
 * Live arbitrage monitoring page.
 *
 * - Displays arbitrage opportunities detected by AI agents
 * - Read-only, low-latency UI
 * - Backend + agents handle execution
 */

// File: frontend/app/yield/arbitrage/page.tsx

"use client";

/**
 * Live arbitrage monitoring page
 */

import React from "react";

import { useArbitrage } from "../../../hooks/useArbitrage";

import { LoadingSpinner } from "../../../components/Shared/LoadingSpinner";
import { ErrorBoundary } from "../../../components/Shared/ErrorBoundary";
import { ArbitrageFeed } from "../../../components/Yield/ArbitrageFeed";

export default function ArbitragePage() {
  return (
    <ErrorBoundary>
      <ArbitrageContent />
    </ErrorBoundary>
  );
}

function ArbitrageContent() {
  const { feed, isLoading, error } = useArbitrage();

  if (isLoading) {
    return <LoadingSpinner label="Loading arbitrage feed…" />;
  }

  if (error) {
    return (
      <div className="p-6 border rounded-md bg-red-50">
        <h3 className="font-semibold text-red-700">
          Failed to load arbitrage feed
        </h3>
        <p className="text-sm text-red-600 mt-2">{error.message}</p>
      </div>
    );
  }

  if (!feed || feed.length === 0) {
    return (
      <div className="p-6 border rounded-md bg-gray-50">
        <h3 className="font-semibold">No arbitrage signals</h3>
        <p className="text-sm text-gray-600 mt-2">
          No active arbitrage opportunities detected.
        </p>
      </div>
    );
  }

  // UI adapter
  const feedForUI: {
  opportunityId: string;
  route: string;
  spread: number;
  confidence: number;
  status: "OPEN" | "EXECUTED" | "EXPIRED";
}[] = feed.map((op) => ({
  opportunityId: op.opportunityId,
  route: Array.isArray(op.route)
    ? op.route.join(" → ")
    : op.route,
  spread: op.spread,
  confidence: op.confidence,
  status:
    op.status === "ACTIVE"
      ? "OPEN"
      : op.status === "EXECUTED"
      ? "EXECUTED"
      : "EXPIRED",
}));



  return (
    <main className="px-6 py-8 space-y-8 max-w-6xl mx-auto">
      <header>
        <h1 className="text-2xl font-semibold">Arbitrage</h1>
        <p className="text-sm text-gray-600 mt-1">
          Live arbitrage opportunities generated by AI agents.
        </p>
      </header>

      <ArbitrageFeed feed={feedForUI} />
    </main>
  );
}
